### ISSUE TITLE
画笔总是超过画板该如何处理？

### ISSUE THREAD

**Issue by xfan1024** [david-pzh/DoubiBot#1]
你好，我在知乎看到这个项目后深受吸引，很感谢开源软件代码和硬件设计文件。
目前我在调试中遇到一些困难希望能够得到帮助

1. doubibot在写字的时候画笔总是超出上边界和左边界，导致卡在画板外，此处应该如何调整？
2. 运行校准代码我的舵机转动角度略大于90度，无法调出完美直角，是否为引起问题？（舵机型号：TS90D）

**Comment by david-pzh** [comment]
你好，所有坐标相关的参数都在control.h里面，可以尝试自己调整，理想情况下机械臂的坐标是非常标准的，具体参数的含义可以自己研究一下control.cpp源码，不是很复杂的




发送自 Windows 10 版邮件应用

发件人: xfan1024
发送时间: 2019年7月7日 上午 5:03
收件人: david-pzh/DoubiBot
抄送: Subscribed
主题: [david-pzh/DoubiBot] 画笔总是超过画板该如何处理？ (#1)

你好，我在知乎看到这个项目后深受吸引，很感谢开源软件代码和硬件设计文件。
目前我在调试中遇到一些困难希望能够得到帮助
1. doubibot在写字的时候画笔总是超出上边界和左边界，导致卡在画板外，此处应该如何调整？
2. 运行校准代码我的舵机转动角度略大于90度，无法调出完美直角，是否为引起问题？（舵机型号：TS90D）

**Comment by david-pzh** [comment]
仓库已经添加了各个参数的示意图片

**Comment by xfan1024** [comment]
已解决，问题应该在于我舵机型号不对。目前解决方法是在Control::GoTo函数中变换pX和pY坐标
